openai_apikey = "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"
assistant_id = "asst_22efcvvMGN6g0ORIBvOgBAqo"
